import configparser

config = configparser.ConfigParser()
config.read('config.ini')

# GENERAL section
DEFAULT_EXCLUDED_PEOPLE = config['GENERAL']['DEFAULT_EXCLUDED_PEOPLE'].split(', ')
APP_NAME = config['GENERAL']['APP_NAME']

# RESOLUTIONS section
MAIN_WINDOW_RESOLUTION = config['RESOLUTIONS']['MAIN_WINDOW_RESOLUTION']
EXCLUDE_WINDOW_RESOLUTION = config['RESOLUTIONS']['EXCLUDE_WINDOW_RESOLUTION']
OPTIONS_WINDOW_RESOLUTION = config['RESOLUTIONS']['OPTIONS_WINDOW_RESOLUTION']
INITIALS_WINDOW_RESOLUTION = config['RESOLUTIONS']['INITIALS_WINDOW_RESOLUTION']

# FILE_NAMES section

HOLIDAY_FILE_NAME = config['FILE_NAMES']['HOLIDAY_FILE_NAME']
SHIFTS_FILE_NAME = config['FILE_NAMES']['SHIFTS_FILE_NAME']
NAMES_INITIALS_FILE_NAME = config['FILE_NAMES']['NAMES_INITIALS_FILE_NAME']
HOLIDAY_SHEET_NAME = config['FILE_NAMES']['HOLIDAY_SHEET_NAME']

# HOLIDAY section
HOLIDAY_START_ROW = int(config['HOLIDAY_FILE']['HOLIDAY_START_ROW'])
HOLIDAY_END_ROW = int(config['HOLIDAY_FILE']['HOLIDAY_END_ROW'])
HOLIDAY_START_COL = int(config['HOLIDAY_FILE']['HOLIDAY_START_COL'])
HOLIDAY_END_COL = int(config['HOLIDAY_FILE']['HOLIDAY_END_COL'])
HOLIDAY_NAMES_START_COL = int(config['HOLIDAY_FILE']['HOLIDAY_NAMES_START_COL'])
UNAVAILABLE_WORDS_LIST = config['HOLIDAY_FILE']['UNAVAILABLE_WORDS_LIST'].split(', ')
HOLIDAY_WORDS_LIST = config['HOLIDAY_FILE']['HOLIDAY_WORDS_LIST'].split(', ')
HOLIDAY_MONTHS_SEARCH_RANGE = int(config['HOLIDAY_FILE']['HOLIDAY_MONTHS_SEARCH_RANGE'])

# WRITE_SHIFTS section
NAMES_START_COL = int(config['WRITE_SHIFTS']['NAMES_START_COL'])
NAMES_START_ROW = int(config['WRITE_SHIFTS']['NAMES_START_ROW'])
WRITE_SHIFTS_FONT = config['WRITE_SHIFTS']['WRITE_SHIFTS_FONT']
WRITE_SHIFTS_FONT_SIZE_NAMES = int(config['WRITE_SHIFTS']['WRITE_SHIFTS_FONT_SIZE_NAMES'])
WRITE_SHIFTS_FONT_SIZE_TITLE = int(config['WRITE_SHIFTS']['WRITE_SHIFTS_FONT_SIZE_TITLE'])
WRITE_SHIFTS_NAMES_FILL = config['WRITE_SHIFTS']['WRITE_SHIFTS_NAMES_FILL']
WRITE_SHIFTS_HOLIDAYS_FILL = config['WRITE_SHIFTS']['WRITE_SHIFTS_HOLIDAYS_FILL']
WRITE_SHIFTS_WORKING_DAY_FILL = config['WRITE_SHIFTS']['WRITE_SHIFTS_WORKING_DAY_FILL']
WRITE_SHIFTS_WORKING_WEEKEND_FILL = config['WRITE_SHIFTS']['WRITE_SHIFTS_WORKING_WEEKEND_FILL']
WRITE_SHIFTS_FILL_TYPE = config['WRITE_SHIFTS']['WRITE_SHIFTS_FILL_TYPE']
WRITE_SHIFTS_CELLS_ALIGNMENT = config['WRITE_SHIFTS']['WRITE_SHIFTS_CELLS_ALIGNMENT']
WRITE_SHIFTS_DISPLAYED_WEEKDAYS = config['WRITE_SHIFTS']['WRITE_SHIFTS_DISPLAYED_WEEKDAYS'].split(', ')
WRITE_SHIFTS_DATES_ROW = int(config['WRITE_SHIFTS']['WRITE_SHIFTS_DATES_ROW'])
WRITE_SHIFTS_NAMES_CELL_HEIGHT = int(config['WRITE_SHIFTS']['WRITE_SHIFTS_NAMES_CELL_HEIGHT'])
WRITE_SHIFTS_NAMES_WIDTH_MARGIN = int(config['WRITE_SHIFTS']['WRITE_SHIFTS_NAMES_WIDTH_MARGIN'])
WRITE_SHIFTS_TABLE_SIDE_STYLE = config['WRITE_SHIFTS']['WRITE_SHIFTS_TABLE_SIDE_STYLE']
WRITE_SHIFTS_DATE_FORMAT = config['WRITE_SHIFTS']['WRITE_SHIFTS_DATE_FORMAT']
WORKING_DAY_NAME = config['WRITE_SHIFTS']['WORKING_DAY_NAME']
NON_WORKING_SATURDAY_NAME = config['WRITE_SHIFTS']['NON_WORKING_SATURDAY_NAME']
NON_WORKING_SUNDAY_NAME = config['WRITE_SHIFTS']['NON_WORKING_SUNDAY_NAME']
HOLIDAY_NAME = config['WRITE_SHIFTS']['HOLIDAY_NAME']
WORKING_SATURDAY_NAME = config['WRITE_SHIFTS']['WORKING_SATURDAY_NAME']
WORKING_SUNDAY_NAME = config['WRITE_SHIFTS']['WORKING_SUNDAY_NAME']
WORKING_HOLIDAY_NAME = config['WRITE_SHIFTS']['WORKING_HOLIDAY_NAME']
WRITE_SHIFTS_TITLE = config['WRITE_SHIFTS']['WRITE_SHIFTS_TITLE']
WRITE_SHIFTS_TITLE_COL = int(config['WRITE_SHIFTS']['WRITE_SHIFTS_TITLE_COL'])
WRITE_SHIFTS_TITLE_ROW = int(config['WRITE_SHIFTS']['WRITE_SHIFTS_TITLE_ROW'])
WRITE_SHIFTS_TITLE_MERGE_CELLS = config['WRITE_SHIFTS']['WRITE_SHIFTS_TITLE_MERGE_CELLS']
WRITE_SHIFTS_FILE_NAME = config['WRITE_SHIFTS']['WRITE_SHIFTS_FILE_NAME']
